from reportlab.lib.pagesizes import A4
from reportlab.lib import colors
from reportlab.platypus import (
    SimpleDocTemplate,
    Paragraph,
    Spacer,
    Image
)
from reportlab.lib.styles import (
    getSampleStyleSheet,
    ParagraphStyle
)
from reportlab.lib.units import inch

import os
import time


def export_pdf_report(
    final_report,
    file_type,
    report_title,
    chart_path=None,
    structured_breakdown=None
):

    os.makedirs("static/reports", exist_ok=True)

    unique_name = f"{int(time.time())}_{report_title}.pdf"

    file_path = os.path.join(
        "static/reports",
        unique_name
    )

    doc = SimpleDocTemplate(
        file_path,
        pagesize=A4,
        rightMargin=40,
        leftMargin=40,
        topMargin=50,
        bottomMargin=40
    )

    styles = getSampleStyleSheet()

    title_style = ParagraphStyle(
        "CustomTitle",
        parent=styles["Title"],
        fontSize=22,
        leading=28,
        spaceAfter=20,
        textColor=colors.HexColor("#1F3C88"),
        alignment=1
    )

    section_style = ParagraphStyle(
        "SectionHeading",
        parent=styles["Heading2"],
        fontSize=15,
        leading=20,
        spaceBefore=12,
        spaceAfter=10,
        textColor=colors.HexColor("#1F3C88")
    )

    body_style = ParagraphStyle(
        "CustomBody",
        parent=styles["BodyText"],
        fontSize=10,
        leading=15,
        spaceAfter=8
    )

    footer_style = ParagraphStyle(
        "Footer",
        parent=styles["BodyText"],
        fontSize=8,
        leading=10,
        alignment=1,
        textColor=colors.grey
    )

    story = []

    # Title
    story.append(
        Paragraph(
            f"{report_title} Analysis Report",
            title_style
        )
    )

    story.append(
        Paragraph(
            "AI-powered intelligent document insights and analysis",
            footer_style
        )
    )

    story.append(Spacer(1, 20))

    # Executive Summary
    if final_report.get("executive_summary"):

        story.append(
            Paragraph(
                "Executive Summary",
                section_style
            )
        )

        story.append(
            Paragraph(
                final_report["executive_summary"],
                body_style
            )
        )

    # Key Insights
    if final_report.get("key_insights"):

        story.append(
            Paragraph(
                "Key Insights",
                section_style
            )
        )

        for point in final_report["key_insights"]:

            story.append(
                Paragraph(
                    f"• {point}",
                    body_style
                )
            )

    # Charts
    if chart_path and isinstance(chart_path, dict):

        story.append(
            Paragraph(
                "Visual Dashboard",
                section_style
            )
        )

        for chart_name, chart_file in chart_path.items():

            if os.path.exists(chart_file):

                try:

                    story.append(
                        Paragraph(
                            chart_name,
                            body_style
                        )
                    )

                    story.append(
                        Image(
                            chart_file,
                            width=6 * inch,
                            height=3 * inch
                        )
                    )

                    story.append(Spacer(1, 12))

                except:
                    pass

    # Recommendations
    if final_report.get("recommendations"):

        story.append(
            Paragraph(
                "Recommendations",
                section_style
            )
        )

        for rec in final_report["recommendations"]:

            story.append(
                Paragraph(
                    f"• {rec}",
                    body_style
                )
            )

    # Structured Breakdown
    if structured_breakdown:

        story.append(
            Paragraph(
                "Detailed Breakdown",
                section_style
            )
        )

        for item in structured_breakdown:

            if isinstance(item, dict):

                text = item.get(
                    "summary",
                    str(item)
                )

                story.append(
                    Paragraph(
                        text,
                        body_style
                    )
                )

                story.append(Spacer(1, 8))

    story.append(Spacer(1, 20))

    story.append(
        Paragraph(
            "Generated by aireportlab",
            footer_style
        )
    )

    # BUILD PDF
    doc.build(story)

    # RETURN FILE PATH
    return file_path
