from reportlab.lib.pagesizes import A4
from reportlab.lib import colors
from reportlab.platypus import SimpleDocTemplate, Paragraph, Spacer, Image
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.lib.units import inch
import os


def export_pdf_report(final_report, file_type, report_title, chart_path=None, structured_breakdown=None):
    os.makedirs("static/reports", exist_ok=True)

    file_path = "static/reports/final_report.pdf"

    doc = SimpleDocTemplate(
        file_path,
        pagesize=A4,
        rightMargin=40,
        leftMargin=40,
        topMargin=50,
        bottomMargin=40
    )

    styles = getSampleStyleSheet()

    # Custom styles
    title_style = ParagraphStyle(
        "CustomTitle",
        parent=styles["Title"],
        fontSize=22,
        leading=28,
        spaceAfter=20,
        textColor=colors.HexColor("#1F3C88"),
        alignment=1
    )

    section_style = ParagraphStyle(
        "SectionHeading",
        parent=styles["Heading2"],
        fontSize=15,
        leading=20,
        spaceBefore=12,
        spaceAfter=10,
        textColor=colors.HexColor("#1F3C88")
    )

    subheading_style = ParagraphStyle(
        "SubHeading",
        parent=styles["Heading3"],
        fontSize=11,
        leading=14,
        spaceBefore=8,
        spaceAfter=6,
        textColor=colors.HexColor("#333333")
    )

    body_style = ParagraphStyle(
        "CustomBody",
        parent=styles["BodyText"],
        fontSize=10,
        leading=15,
        spaceAfter=8
    )

    footer_style = ParagraphStyle(
        "Footer",
        parent=styles["BodyText"],
        fontSize=8,
        leading=10,
        alignment=1,
        textColor=colors.grey
    )

    story = []

    # Title
    story.append(Paragraph(f"{report_title} Analysis Report", title_style))
    story.append(Paragraph("AI-powered intelligent document insights and analysis", footer_style))
    story.append(Spacer(1, 20))

    # Executive Summary
    if final_report.get("executive_summary"):
        story.append(Paragraph("Executive Summary", section_style))
        story.append(Paragraph(final_report["executive_summary"], body_style))
        story.append(Spacer(1, 12))

    # Key Insights
    if final_report.get("key_insights"):
        story.append(Paragraph("Key Insights", section_style))
        for point in final_report["key_insights"]:
            story.append(Paragraph(f"• {point}", body_style))
        story.append(Spacer(1, 12))

    # Visual Dashboard
    if chart_path:
        story.append(Paragraph("Visual Dashboard", section_style))
        story.append(Spacer(1, 8))

        for chart_name, chart_file in chart_path.items():
            if os.path.exists(chart_file):
                story.append(Paragraph(f"{chart_name.title()} Chart", subheading_style))
                story.append(Image(chart_file, width=6.2 * inch, height=3.2 * inch))
                story.append(Spacer(1, 14))

    # Recommendations
    if final_report.get("recommendations"):
        story.append(Paragraph("Recommendations", section_style))
        for item in final_report["recommendations"]:
            story.append(Paragraph(f"• {item}", body_style))

    # Structured Breakdown
    if structured_breakdown:
        if file_type in ['csv', 'excel','json_tabular']:
            story.append(Spacer(1, 12))
            story.append(Paragraph("Column-wise Summary", section_style))

            for item in structured_breakdown:
                text = (
                    f"<b>{item['column']}</b> ({item['type']}) — "
                    f"Missing: {item['missing_percent']}%, "
                    f"Unique: {item['unique_values']}<br/>"
                    f"{item['summary']}"
                )
                story.append(Paragraph(text, body_style))
                story.append(Spacer(1, 8))

        elif file_type in ['pdf', 'docx','json_text','txt']:
            story.append(Spacer(1, 12))
            story.append(Paragraph("Page-wise Summary", section_style))

            for item in structured_breakdown:
                text = f"<b>Page {item['page']}</b><br/>{item['summary']}"
                story.append(Paragraph(text, body_style))
                story.append(Spacer(1, 8))
                
        story.append(Spacer(1, 20))
        story.append(Paragraph("Generated by aireportlab", footer_style))

        doc.build(story)

        return file_path